export const IGNORED_DEAL_BOTS = [
  { id: "t1nslxql4pck5pq7hddlzym3orxlx35wkepzjkm3i", alias_id: "f0112" },
  { id: "t1stghxhdp2w53dym2nz2jtbpk6ccd4l2lxgmezlq", alias_id: "f0113" },
  { id: "t1mcr5xkgv4jdl3rnz77outn6xbmygb55vdejgbfi", alias_id: "f0114" },
  { id: "t1qiqdbbmrdalbntnuapriirduvxu5ltsc5mhy7si", alias_id: "f010089" },
];

// TODO(jim): Get this from the static miners list.
export const PRIMARY_MINERS = [
  "f016303",
  "f016304",
  "f016305",
  "f016305",
  "f016309",
];

export const STATIC = ["/api/static-global-miners"];

export const ANALYSIS = [
  "/api/storage-unique-client-addresses",
  "/api/storage-unique-cids",
  "/api/storage-average-real-deal-size",
  "/api/storage-total-data-stored",
  "/api/storage-total-deals",
  "/api/storage-total-verified-data-stored",
  "/api/storage-total-unverified-data-stored",
  "/api/storage-clients",
  "/api/storage-clients-with-addresses",
  "/api/storage-leaderboard",
];

export const CHAIN = [
  "/api/chain-visualizer-blocks-view",
  `/api/chain-visualizer-blocks-view?&where=[["where", "miner", "=", "t02305"]]`,
  "/api/chain-visualizer-blocks-with-parents-view",
  "/api/chain-visualizer-chain-data-view",
  "/api/chain-visualizer-orphans-view",
];

export const ROUTES = [
  "/api/actor-states",
  "/api/actors",
  "/api/block-cids",
  "/api/block-drand-entries",
  "/api/block-messages",
  "/api/block-parents",
  "/api/blocks-synced",
  "/api/blocks",
  "/api/chain-economics",
  "/api/chain-mpool",
  "/api/chain-power",
  "/api/chain-reward",
  "/api/cpu",
  "/api/disk",
  "/api/diskio",
  "/api/drand-entries",
  "/api/id-address-map",
  "/api/kernel",
  "/api/linux-sysctl-fs",
  "/api/lotus-block-received",
  "/api/lotus-block-success",
  "/api/lotus-block-validation-ms",
  "/api/lotus-chain-node-height",
  "/api/lotus-chain-node-worker-height",
  "/api/lotus-message-failure",
  "/api/lotus-message-published",
  "/api/lotus-message-received",
  "/api/lotus-message-success",
  "/api/lotus-peer-count",
  "/api/lotus-process-cpu-cgo-calls",
  "/api/lotus-process-cpu-goroutines",
  "/api/lotus-process-heap-alloc",
  "/api/lotus-process-heap-idle",
  "/api/lotus-process-heap-inuse",
  "/api/lotus-process-heap-objects",
  "/api/lotus-process-heap-release",
  "/api/lotus-process-memory-alloc",
  "/api/lotus-process-memory-frees",
  "/api/lotus-process-memory-lookups",
  "/api/lotus-process-memory-malloc",
  "/api/lotus-process-stack-inuse",
  "/api/lotus-process-stack-mcache-inuse",
  "/api/lotus-process-sys-heap",
  "/api/lotus-process-sys-memory-alloc",
  "/api/lotus-process-sys-stack-mcache",
  "/api/lotus-process-sys-stack-mspan",
  "/api/lotus-process-sys-stack",
  "/api/lotus-process-total-memory-alloc",
  "/api/lotus-pubsub-delivered",
  "/api/lotus-pubsub-drop-rpc",
  "/api/lotus-pubsub-duplicate",
  "/api/lotus-pubsub-published",
  "/api/lotus-pubsub-recv-rpc",
  "/api/lotus-pubsub-rejected",
  "/api/lotus-rpc-request-error",
  "/api/lotus-rpc-response-error",
  "/api/market-deal-proposals",
  "/api/market-deal-states",
  "/api/mem",
  "/api/messages",
  `/api/messages?where=[[”where”, “miner”, “=”, “t02305”]]`,
  "/api/miner-info",
  "/api/miner-power",
  "/api/miner-sector-events",
  "/api/minerid-dealid-sectorid",
  "/api/mpool-messages",
  "/api/nstat",
  "/api/processes",
  "/api/receipts",
  "/api/sector-info",
  "/api/sector-precommit-info",
  "/api/state-heights",
  "/api/swap",
  "/api/system",
  "/api/top-miners-by-base-reward-max-height",
  "/api/top-miners-by-base-reward",
];
